# very raw makefile to produce the website


all: site_generation

site_generation:
	../site-generator.rb


# disabled because im afraid of doing automatic "rm -rf"
clean:
	rm -rf ../www.web4web.tv/dst/