#!/usr/bin/ruby
#
# \par Brief Description


require 'tvrover_t'
#require "vlc_restreamer_t"
require 'rubygems'
require 'json'
require 'pp'

rstream_arr	= Tvrover.parse_onepage("world/France"	, "http://www.tvrover.com/france/tv-france.html")
#rstream_arr	= Tvrover.parse_onepage("world/Belgium"	, "http://www.tvrover.com/belgium/tv-belgium.html")
#rstream_arr	= Tvrover.parse_onepage("world/Argentina", "http://www.tvrover.com/argentina/tv-argentina.html")
#rstream_arr	= Tvrover.parse_onepage("world"		, "http://www.tvrover.com")
#rstream_arr	= Tvrover.parse_onepage("world/USA"	, "http://www.tvrover.com/usa/tv-usa.html")
#rstream_arr	= Tvrover.parse_onepage("world/Columbia", "http://www.tvrover.com/columbia/tv-columbia.html")

# insert an autogenerated cast_name for each item of rstream_arr
rstream_arr.collect! { |item|
	item['cast_name']	= item['human_name'].gsub(' ', '_') + ".flv"
	item
}

#pp rstream_arr
puts JSON.pretty_generate(rstream_arr)
