# very raw makefile
#

MXMLC=mxmlc
MXMLC_OPTS=-compiler.optimize -compiler.strict -compiler.as3

MAIN_SRC=readwebcam.as
MAIN_OUT=bin-debug/readwebcam.swf

all:
	$(MXMLC) $(MXMLC_OPTS) $(MAIN_SRC) -output $(MAIN_OUT)
